### ISSUE TITLE
There was a problem exporting the yolov5 dataset/ but when i export the yolov3/4 dataset  is normal

### ISSUE THREAD

**Issue by xiaocaof** [HumanSignal/label-studio-converter#293]
Traceback (most recent call last):

  File "/root/anaconda3/envs/label-studio/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch

    response = handler(request, *args, **kwargs)

  File "/root/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper

    return bound_method(*args, **kwargs)

  File "/root/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio/data_export/api.py", line 200, in get

    export_stream, content_type, filename = DataExport.generate_export_file(

  File "/root/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio/data_export/models.py", line 161, in generate_export_file

    converter.convert(input_json, tmp_dir, output_format, is_dir=False)

  File "/root/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio_converter/converter.py", line 285, in convert

    self.convert_to_yolov5(

  File "/root/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio_converter/converter.py", line 1060, in convert_to_yolov5

    for index, label in enumerate(item['output']['label']):

KeyError: 'label'    
how can i solve it !!!! very thanks!!!!

**Comment by xiaocaof** [comment]
has been solved
